name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: pnpm/action-setup@v6
      - run: pnpm install
      - run: pnpm lint:all
      - run: pnpm pack:sheriff
      - run: pnpm test:ci
      - run: ./run-integration-tests.sh
