name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: npm install -g yalc
      - run: pnpm install
      - run: pnpm lint:all
      - run: pnpm link:sheriff
      - run: pnpm test:ci
      - run: cd test-projects/angular-i && pnpm install && npx ng lint
      - run: cd test-projects/angular-ii && pnpm install && npx ng lint
      - run: cd test-projects/angular-iii && pnpm install && npx ng lint
      - run: ./run-integration-tests.sh
